apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis-config: |
    # Redis configuration
    bind 0.0.0.0
    protected-mode no
    port 6379
    dir /redis-master-data
    appendonly yes
